Add KDE Neon support

diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -59,6 +59,11 @@ if [ -z "$packageName" ]; then
     exit 1
 fi
 
+QDBUS_BIN=$(command -v qdbus || command -v qdbus6) || {
+    echo "qdbus not found" >&2
+    exit 1
+}
+
 # Remove package
 INSTALL_DIR="$HOME/.local/share/plasma/plasmoids/$packageName"
 if [ -d "$INSTALL_DIR" ]; then
@@ -67,7 +72,7 @@ if [ -d "$INSTALL_DIR" ]; then
     
     # Remove plasmoid instances
     log "Removing plasmoid instances..."
-    qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "
+    "$QDBUS_BIN" org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "
         var allDesktops = desktops();
         for (var i = 0; i < allDesktops.length; i++) {
             var d = allDesktops[i];
